export const SliderData = [
  {
    index: 0,
    id: '01',
    image: `url('/assets/img/Bitmap.jpg')`,
    title: 'Work from Home',
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sed neque lobortis, suscipit lorem`,
    call: 'wfh',
    video: '/assets/videos/Work-From-Home.mp4',
  },
  {
    index: 1,
    id: '02',
    image: `url('/assets/img/mainBg.png')`,
    title: 'Continued Innovation',
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sed neque lobortis.`,
    call: 'continued-innovation',
    video: '/assets/videos/Innovation.mp4',
  },
  {
    index: 2,
    id: '03',
    // status: 'New',
    image: `url('/assets/img/Next-Gen-Control-Room.png')`,
    title: 'Control Room',
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sed neque lobortis.`,
    call: 'control',
    video: '/assets/videos/ControlRoom.mp4',
  },
  {
    index: 3,
    id: '04',
    image: `url('/assets/img/Redefining-Learning-Spaces.png')`,
    title: 'Redefining Learning Spaces',
    description: `Virtually experience LG's technology in unique vertical spaces.`,
    call: 'redefining-Learning-paces',
    video: '/assets/videos/LGHomePageWalkThru.mp4',
  },
  {
    index: 4,
    id: '05',
    image: `url('/assets/img/Corporate-Solutions.png')`,
    title: 'Corporate Solutions',
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sed neque lobortis.`,
    call: 'corporate-solutions',
    video: '/assets/videos/Corporate.mp4',
  },
  {
    index: 5,
    id: '06',
    image: `url('/assets/img/Next-Gen-Control-Room.png')`,
    title: 'Education',
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sed neque lobortis, suscipit lorem`,
    call: 'education',
    video: '/assets/videos/EducationDesktop.mp4',
  },
  {
    index: 6,
    id: '07',
    image: `url('/assets/img/Outdoor.jpg')`,
    title: 'Outdoor',
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sed neque lobortis, suscipit lorem`,
    call: 'outdoor',
    video: '/assets/videos/Outdoor.mp4',
  },
  {
    index: 7,
    id: '08',
    image: `url('/assets/img/Corporate-Solutions.png')`,
    title: 'Luxury Flagship Store',
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sed neque lobortis.`,
    call: 'luxury',
    video: '/assets/videos/LGHomePageWalkThru.mp4',
  },
  {
    index: 8,
    id: '09',
    image: `url('/assets/img/FastFood.jpg')`,
    title: 'Fast Food Restaurant',
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sed neque lobortis, suscipit lorem`,
    call: 'fast',
    video: '/assets/videos/LGHomePageWalkThru.mp4',
  },
  {
    index: 9,
    id: '10',
    image: `url('/assets/img/DriveThruClinic.jpg')`,
    title: 'Drive Thru Clinic',
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sed neque lobortis.`,
    call: 'drive',
    video: '/assets/videos/LGHomePageWalkThru.mp4',
  },
  {
    index: 10,
    id: '11',
    image: `url('/assets/img/HospitalLobby.jpg')`,
    title: 'Hospital Lobby',
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sed neque lobortis, suscipit lorem`,
    call: 'hospital',
    video: '/assets/videos/Hospital-Lobby.mp4',
  },
  {
    index: 11,
    id: '12',
    image: `url('/assets/img/Supermarket.jpg')`,
    title: 'Grocery Store',
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sed neque lobortis.`,
    call: 'grocery-store',
    video: '/assets/videos/Supermarket.mp4',
  },
  {
    index: 12,
    id: '13',
    image: `url('/assets/img/HomeOffice.jpg')`,
    title: 'Home Office',
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sed neque lobortis, suscipit lorem`,
    call: 'home-office',
    video: '/assets/videos/LGHomePageWalkThru.mp4',
  },
  {
    index: 13,
    id: '14',
    image: `url('/assets/img/HomeCinema.jpg')`,
    title: 'Home Cinema',
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sed neque lobortis.`,
    call: 'home-cinema',
    video: '/assets/videos/LGHomePageWalkThru.mp4',
  },
  {
    index: 14,
    id: '15',
    image: `url('/assets/img/Next-Gen-Control-Room.png')`,
    title: 'Metro',
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sed neque lobortis.`,
    call: 'metro',
    video: '/assets/videos/Metro.mp4',
  },
  {
    index: 15,
    id: '16',
    image: `url('/assets/img/Cinema.jpg')`,
    title: 'Cinema',
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sed neque lobortis, suscipit lorem`,
    call: 'cinema',
    video: '/assets/videos/LGHomePageWalkThru.mp4',
  },
];
